name: Build macOS App

on:
  push:
    branches:
      - main  # Запускать при каждом пуше в основную ветку

jobs:
  build:
    runs-on: macos-latest  # Используем macOS для сборки

    steps:
      - name: Check out the code
        uses: actions/checkout@v2  # Клонируем репозиторий

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Указываем версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt  # Устанавливаем зависимости из requirements.txt

      - name: Build .app with PyInstaller
        run: |
          # Создание .app файла для macOS
          pyinstaller --onefile --windowed --add-data "damage_calculator.py:./damage_calculator.app/Contents/Resources" damage_calculator.py

      - name: Upload macOS app
        uses: actions/upload-artifact@v4
        with:
          name: damage_calculator
          path: dist/damage_calculator.app  # Путь к сгенерированному .app файлу